# Generated by Django 5.2.12 on 2026-03-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pokemon_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['id']},
        ),
    ]
