# Generated by Django 4.2.29 on 2026-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ability_name_alter_move_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
